### ISSUE TITLE
No explanation for color coding in infographics page.

### ISSUE THREAD

**Issue by kushagrasrivastva-NEC** [SmartInfrastructures/fiware-lab-infographics#1]
Infographics page (http://infographic.lab.fiware.org/) shows two color representation mainly orange and grey. 
Status lab page (http://status.lab.fiware.org/) shows three color representation namely green, yellow, red and also, grey. 
However, there is no explanation available for these color coding on infographics page itself. 
Only, meaning of grey color is available in status lab page.

In user-guide.rst also, there is no explanation available for different color coding namely green, yellow, red, and orange. Only information available for grey color coding.

Kindly include the meaning of different color , so as to get better understanding.

**Comment by K4s14** [comment]
The [user guide](https://github.com/SmartInfrastructures/fi-lab-infographics/blob/master/doc/user-guide.rst) and the Status lab page (http://status.lab.fiware.org/) have been updated with an explanation for the different color coding.
